-- =====================================================
-- DOCUFLOW - ESQUEMA DE BASE DE DATOS SUPABASE
-- =====================================================

-- =====================================================
-- EXTENSIONES
-- =====================================================
create extension if not exists "uuid-ossp";

-- =====================================================
-- TABLA: PROFILES (extiende auth.users)
-- =====================================================
create table public.profiles (
    id uuid references auth.users on delete cascade not null primary key,
    username text unique not null,
    full_name text,
    role text default 'usuario' check (role in ('admin', 'colaborador', 'usuario')) not null,
    avatar_url text,
    preferences jsonb default '{}'::jsonb,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- =====================================================
-- TABLA: DOCUMENTS
-- =====================================================
create table public.documents (
    id bigint generated by default as identity primary key,
    filename text not null,
    file_type text,
    file_path text not null,
    size bigint,
    uploaded_by uuid references public.profiles(id) on delete set null,
    uploaded_at timestamptz default now(),
    updated_at timestamptz,
    is_deleted boolean default false
);

-- =====================================================
-- TABLA: COMMENTS
-- =====================================================
create table public.comments (
    id bigint generated by default as identity primary key,
    content text not null,
    document_id bigint references public.documents(id) on delete cascade,
    author_id uuid references public.profiles(id) on delete set null,
    author_username text,
    is_task boolean default false,
    assignees text[] default '{}',
    completed boolean default false,
    created_at timestamptz default now(),
    updated_at timestamptz,
    last_edited_by text
);

-- =====================================================
-- TABLA: LOGS
-- =====================================================
create table public.logs (
    id bigint generated by default as identity primary key,
    action text not null,
    user_id uuid references public.profiles(id) on delete set null,
    username text,
    document_id bigint,
    target_username text,
    details text,
    ip_address text,
    created_at timestamptz default now()
);

-- =====================================================
-- TABLA: NOTIFICATIONS
-- =====================================================
create table public.notifications (
    id bigint generated by default as identity primary key,
    title text not null,
    message text,
    type text default 'info' check (type in ('info', 'warning', 'error', 'success', 'announcement')),
    priority text default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
    user_id uuid references public.profiles(id) on delete cascade,
    is_global boolean default false,
    is_active boolean default true,
    metadata jsonb,
    created_at timestamptz default now(),
    expires_at timestamptz,
    created_by text
);

-- =====================================================
-- TABLA: REFRESH TOKENS (custom, para sesión larga)
-- =====================================================
create table public.refresh_tokens (
    id bigint generated by default as identity primary key,
    token text unique not null,
    user_id uuid references auth.users on delete cascade not null,
    expires_at timestamptz not null,
    revoked boolean default false,
    created_at timestamptz default now()
);

-- =====================================================
-- ÍNDICES PARA MEJORAR PERFORMANCE
-- =====================================================
create index idx_documents_uploaded_by on public.documents(uploaded_by);
create index idx_documents_uploaded_at on public.documents(uploaded_at desc);
create index idx_documents_filename on public.documents(filename);

create index idx_comments_document_id on public.comments(document_id);
create index idx_comments_author_id on public.comments(author_id);
create index idx_comments_is_task on public.comments(is_task);

create index idx_logs_user_id on public.logs(user_id);
create index idx_logs_action on public.logs(action);
create index idx_logs_created_at on public.logs(created_at desc);

create index idx_notifications_user_id on public.notifications(user_id);
create index idx_notifications_is_global on public.notifications(is_global);
create index idx_notifications_created_at on public.notifications(created_at desc);

create index idx_refresh_tokens_user_id on public.refresh_tokens(user_id);
create index idx_refresh_tokens_token on public.refresh_tokens(token);

-- =====================================================
-- FUNCIONES UTILITARIAS
-- =====================================================

-- Función para obtener el rol actual del usuario
create or replace function public.get_current_user_role()
returns text
language plpgsql
security definer
as $$
declare
    user_role text;
begin
    select role into user_role
    from public.profiles
    where id = auth.uid();
    
    return coalesce(user_role, 'usuario');
end;
$$;

-- Función para verificar si el usuario puede editar documentos (admin o colaborador)
create or replace function public.can_edit_documents()
returns boolean
language plpgsql
security definer
as $$
declare
    user_role text;
begin
    select role into user_role
    from public.profiles
    where id = auth.uid();
    
    return user_role in ('admin', 'colaborador');
end;
$$;

-- Función para verificar si el usuario puede gestionar usuarios (solo admin)
create or replace function public.can_manage_users()
returns boolean
language plpgsql
security definer
as $$
declare
    user_role text;
begin
    select role into user_role
    from public.profiles
    where id = auth.uid();
    
    return user_role = 'admin';
end;
$$;

-- Función para verificar si el usuario puede ver logs (solo admin)
create or replace function public.can_view_logs()
returns boolean
language plpgsql
security definer
as $$
declare
    user_role text;
begin
    select role into user_role
    from public.profiles
    where id = auth.uid();
    
    return user_role = 'admin';
end;
$$;

-- Función para verificar si el usuario puede eliminar documentos
create or replace function public.can_delete_document(doc_uploaded_by uuid)
returns boolean
language plpgsql
security definer
as $$
declare
    user_role text;
    current_user_id uuid;
begin
    current_user_id := auth.uid();
    
    select role into user_role
    from public.profiles
    where id = current_user_id;
    
    -- admin puede eliminar cualquier documento
    if user_role = 'admin' then
        return true;
    end if;
    
    -- colaborador puede eliminar sus propios documentos
    if user_role = 'colaborador' and doc_uploaded_by = current_user_id then
        return true;
    end if;
    
    -- usuario no puede eliminar
    return false;
end;
$$;

-- Función para verificar si el usuario puede editar comentarios
create or replace function public.can_edit_comment(comment_author_id uuid)
returns boolean
language plpgsql
security definer
as $$
declare
    user_role text;
    current_user_id uuid;
begin
    current_user_id := auth.uid();
    
    select role into user_role
    from public.profiles
    where id = current_user_id;
    
    -- admin puede editar cualquier comentario
    if user_role = 'admin' then
        return true;
    end if;
    
    -- colaborador y usuario pueden editar sus propios comentarios
    if comment_author_id = current_user_id then
        return true;
    end if;
    
    return false;
end;
$$;



-- Función para actualizar updated_at automáticamente
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Trigger para profiles
create trigger update_profiles_updated_at
    before update on public.profiles
    for each row execute function update_updated_at_column();

-- Trigger para documents
create trigger update_documents_updated_at
    before update on public.documents
    for each row execute function update_updated_at_column();

-- Trigger para comments
create trigger update_comments_updated_at
    before update on public.comments
    for each row execute function update_updated_at_column();

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Habilitar RLS
alter table public.profiles enable row level security;
alter table public.documents enable row level security;
alter table public.comments enable row level security;
alter table public.logs enable row level security;
alter table public.notifications enable row level security;
alter table public.refresh_tokens enable row level security;

-- =====================================================
-- POLÍTICAS RLS - PROFILES
-- =====================================================

-- Todos pueden leer perfiles
create policy "Anyone can read profiles"
    on public.profiles for select
    using (true);

-- Solo admin puede actualizar cualquier perfil (gestión de usuarios)
-- Los usuarios pueden actualizar su propio perfil excepto el rol
create policy "Admin can manage all profiles, users own profile"
    on public.profiles for update
    using (
        public.can_manage_users()
        or 
        (id = auth.uid())
    );

-- Solo admin puede crear perfiles manualmente
create policy "Only admin can insert profiles"
    on public.profiles for insert
    with check (
        public.can_manage_users()
    );

-- Solo admin puede eliminar perfiles
create policy "Only admin can delete profiles"
    on public.profiles for delete
    using (
        public.can_manage_users()
    );

-- =====================================================
-- POLÍTICAS RLS - DOCUMENTS
-- =====================================================

-- Todos los usuarios autenticados pueden leer documentos
create policy "Authenticated users can read documents"
    on public.documents for select
    using (
        auth.role() = 'authenticated'
        and is_deleted = false
    );

-- Admin y colaborador pueden crear documentos
create policy "Admin and collaborator can create documents"
    on public.documents for insert
    with check (
        auth.role() = 'authenticated'
        and public.can_edit_documents()
    );

-- Admin puede actualizar cualquier documento, colaborador solo sus propios
create policy "Admin can update any document, collaborator own documents"
    on public.documents for update
    using (
        (public.get_current_user_role() = 'admin')
        or 
        (public.get_current_user_role() = 'colaborador' and uploaded_by = auth.uid())
    );

-- Solo admin y dueño (colaborador) pueden eliminar documentos
create policy "Admin or owner can delete documents"
    on public.documents for delete
    using (
        public.can_delete_document(uploaded_by)
    );

-- =====================================================
-- POLÍTICAS RLS - COMMENTS
-- =====================================================

-- Todos pueden leer comentarios
create policy "Anyone can read comments"
    on public.comments for select
    using (true);

-- Usuarios autenticados pueden crear comentarios (todos los roles)
create policy "Authenticated users can create comments"
    on public.comments for insert
    with check (
        auth.role() = 'authenticated'
    );

-- Admin puede editar cualquier comentario, autor puede editar sus propios
create policy "Admin or author can update comments"
    on public.comments for update
    using (
        public.can_edit_comment(author_id)
    );

-- Admin puede eliminar cualquier comentario, autor puede eliminar sus propios
create policy "Admin or author can delete comments"
    on public.comments for delete
    using (
        public.can_edit_comment(author_id)
    );

-- =====================================================
-- POLÍTICAS RLS - LOGS
-- =====================================================

-- Solo admin puede ver logs
create policy "Only admin can view logs"
    on public.logs for select
    using (
        public.can_view_logs()
    );

-- Sistema puede insertar logs
create policy "System can insert logs"
    on public.logs for insert
    with check (true);

-- =====================================================
-- POLÍTICAS RLS - NOTIFICATIONS
-- =====================================================

-- Usuarios ven sus propias notificaciones o globales
create policy "Users see own or global notifications"
    on public.notifications for select
    using (
        user_id = auth.uid()
        or is_global = true
    );

-- Solo admin puede crear notificaciones globales o para otros usuarios
-- Los usuarios pueden crear notificaciones para sí mismos
create policy "Admin can create any notification, users own"
    on public.notifications for insert
    with check (
        public.can_manage_users()
        or 
        user_id = auth.uid()
    );

-- Solo admin puede actualizar cualquier notificación
-- Usuarios pueden actualizar sus propias notificaciones
create policy "Admin can update any notification, users own"
    on public.notifications for update
    using (
        public.can_manage_users()
        or 
        user_id = auth.uid()
    );

-- Solo admin puede eliminar cualquier notificación
-- Usuarios pueden eliminar sus propias notificaciones
create policy "Admin can delete any notification, users own"
    on public.notifications for delete
    using (
        public.can_manage_users()
        or 
        user_id = auth.uid()
    );

-- =====================================================
-- POLÍTICAS RLS - REFRESH TOKENS
-- =====================================================

-- Usuario puede gestionar sus propios refresh tokens
create policy "Users manage own tokens"
    on public.refresh_tokens for all
    using (user_id = auth.uid());

-- =====================================================
-- FUNCIONES PERSONALIZADAS (RPC)
-- =====================================================

-- Obtener perfil del usuario actual
create or replace function get_current_profile()
returns table (
    id uuid,
    username text,
    full_name text,
    role text,
    avatar_url text,
    created_at timestamptz
)
language plpgsql
security definer
as $$
begin
    return query
    select p.id, p.username, p.full_name, p.role, p.avatar_url, p.created_at
    from public.profiles p
    where p.id = auth.uid();
end;
$$;

-- Obtener estadísticas del dashboard
create or replace function get_dashboard_stats()
returns jsonb
language plpgsql
security definer
as $$
declare
    result jsonb;
begin
    select jsonb_build_object(
        'total_files', (select count(*) from public.documents where is_deleted = false),
        'total_users', (select count(*) from public.profiles),
        'total_comments', (select count(*) from public.comments),
        'total_notifications', (select count(*) from public.notifications where is_active = true),
        'total_storage', (select coalesce(sum(size), 0) from public.documents where is_deleted = false),
        'recent_files', (
            select coalesce(jsonb_agg(
                jsonb_build_object(
                    'id', id,
                    'filename', filename,
                    'file_type', file_type,
                    'size', size,
                    'uploaded_at', uploaded_at
                )
            ), '[]'::jsonb)
            from (
                select id, filename, file_type, size, uploaded_at
                from public.documents 
                where is_deleted = false
                order by uploaded_at desc limit 5
            ) as recent
        ),
        'recent_activities', (
            select coalesce(jsonb_agg(
                jsonb_build_object(
                    'id', id,
                    'action', action,
                    'username', username,
                    'document_id', document_id,
                    'created_at', created_at
                )
            ), '[]'::jsonb)
            from (
                select id, action, username, document_id, created_at
                from public.logs
                order by created_at desc limit 10
            ) as recent
        )
    ) into result;

    return result;
end;
$$;

-- Buscar documentos
create or replace function search_documents(search_query text, limit_count int default 10)
returns table (
    id bigint,
    filename text,
    file_type text,
    size bigint,
    uploaded_by uuid,
    uploaded_at timestamptz
)
language plpgsql
security definer
as $$
begin
    return query
    select d.id, d.filename, d.file_type, d.size, d.uploaded_by, d.uploaded_at
    from public.documents d
    where d.is_deleted = false
    and d.filename ilike '%' || search_query || '%'
    order by d.uploaded_at desc
    limit limit_count;
end;
$$;

-- Completar tarea (comentario)
create or replace function complete_task(task_id bigint, completed boolean default true)
returns void
language plpgsql
security definer
as $$
begin
    update public.comments
    set completed = completed, updated_at = now()
    where id = task_id and is_task = true;
end;
$$;

-- Buscar documentos con filtros de fecha
create or replace function search_documents_with_filters(
    search_query text default null,
    start_date timestamptz default null,
    end_date timestamptz default null,
    limit_count int default 10
)
returns table (
    id bigint,
    filename text,
    file_type text,
    size bigint,
    uploaded_by uuid,
    uploaded_at timestamptz
)
language plpgsql
security definer
as $$
begin
    return query
    select d.id, d.filename, d.file_type, d.size, d.uploaded_by, d.uploaded_at
    from public.documents d
    where d.is_deleted = false
    and (
        search_query is null 
        or d.filename ilike '%' || search_query || '%'
    )
    and (
        start_date is null 
        or d.uploaded_at >= start_date
    )
    and (
        end_date is null 
        or d.uploaded_at <= end_date
    )
    order by d.uploaded_at desc
    limit limit_count;
end;
$$;

-- =====================================================
-- TRIGGER: Crear perfil automáticamente al registrar usuario
-- =====================================================
create or replace function handle_new_user()
returns trigger as $$
declare
    username_from_email text;
begin
    -- Generar username desde email
    username_from_email := split_part(new.email, '@', 1);
    
    -- Si el username ya existe, agregar sufijo único
    if exists (select 1 from public.profiles where username = username_from_email) then
        username_from_email := username_from_email || '_' || left(new.id::text, 8);
    end if;

    -- Crear perfil con rol 'usuario' por defecto (más restrictivo)
    insert into public.profiles (id, username, full_name, role)
    values (new.id, username_from_email, new.raw_user_meta_data->>'full_name', 'usuario');

    return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure handle_new_user();

-- =====================================================
-- CONFIGURACIÓN DE REALTIME
-- =====================================================
alter publication supabase_realtime add table public.notifications;
alter publication supabase_realtime add table public.comments;

-- =====================================================
-- COMENTARIOS FINALES
-- =====================================================
-- Este esquema incluye:
-- - 6 tablas principales con RLS
-- - Índices optimizados
-- - Funciones RPC útiles
-- - Triggers automáticos
-- - Realtime para notificaciones y comentarios
--
-- Para ejecutar en Supabase:
-- 1. Ir al SQL Editor
-- 2. Copiar y ejecutar este script
-- 3. Configurar Storage bucket "documents"
-- 4. Desplegar Edge Functions
